### PR TITLE
Fixes two minor bugs to make the plugin work on iOS

### PR DESCRIPTION
**Pull request by walski**
@fh please merge

### CODE REVIEW

**Comment by walski** [comment]
Excuse me, this PR was planned as an internal one first. Anyway, this solves two bugs I had when setting up and building the plugin on iOS so maybe you want to merge this, too :)

**Comment by till** [comment]
I lol'd hard. ;)))

@fh :trollface:

**Comment by samzilverberg** [comment]
will try this out on the weekend.
thanks

**Comment by till** [comment]
Thank you, @samzilverberg! :)

**Pull request merged**
