### PR TITLE
Add the TimeEvent methods

### PR DESCRIPTION
**Pull request by JonSmart**
I have added a start and stop TimeEvent methods.  Mixpanel supports TimeEvent to be fired prior to a track event to add duration to the actual event.  This can be quite useful for tracking how long things take or user dwell times in sections of your App.  I added the stop method as a simple method rather than using Track, but you can use track as long as the eventName is the same.

Hope that makes sense.

### CODE REVIEW

**Comment by samzilverberg** [comment]
hey there sorry for the delay, i didnt have a lot of time for maintaining this project in the last month or two.
I will take a look at this in the next couple of days.

Thanks a lot for your contribution!

**Comment by JonSmart** [comment]
No Problems. Happy to help if my contribution has helped. Your plugin definitely helped us. Thank you. 

All the best,
Jonathan Smart
+44 7976 354770

**Comment by samzilverberg** [comment]
hi @JonSmart , i've finally had some time to review and got some suggested changes:

- stopTimeEvent: i'd like to remove this
- startTimeEvent: would rename to just timeEvent

**why?**
the mixpanel api instructs to call "time event" followed by a "track" with the same event name (properties are also allowed).
I feel its best to have the plugin api as close as possible to the real mixpanel api. 
that way a developer reading the mixpanel documentation can directly use the plugin without effort.
in this case there's an extra 'stop time event' method which is undocumented in mixpanel api and might confuse a developer as to what and why its in the plugin.

tell me what you think about it and if you got time to do it.
if you don't have time i would probably pull your forked branch and do it myself sometime soon.

I got another question about the typescript declarations file as I myself am not yet using typescript. 
would it be enough and helpful to others to merge just this file?
what was your thought behind committing it?

**Comment by JonSmart** [comment]
> i've finally had some time to review and got some suggested changes:
> 
> stopTimeEvent: i'd like to remove this
> startTimeEvent: would rename to just timeEvent
> why?
> the mixpanel api instructs to call "time event" followed by a "track" with the same event name (properties are also allowed).
> I feel its best to have the plugin api as close as possible to the real mixpanel api. 
> that way a developer reading the mixpanel documentation can directly use the plugin without effort.
> in this case there's an extra 'stop time event' method which is undocumented in mixpanel api and might confuse a developer as to what and why its in the plugin.
> 
> tell me what you think about it and if you got time to do it.
> if you don't have time i would probably pull your forked branch and do it myself sometime soon.
> 
I agree, I did it originally to be clear (as I miss read their API in a rush), however your logic makes perfect sense, I have some time later this week so will make the changes and let you know.
> I got another question about the typescript declarations file as I myself am not yet using typescript. 
> would it be enough and helpful to others to merge just this file?
> 
I think so, either that or register the file with definitely typed, I added it there because it is needed to make my project work and thought it would be useful to others as it means they get good definitions.  I think there is still room for improvements as I would prefer :any not to appear in it, but I will try and improve this over time too.  
> 
> what was your thought behind committing it?
> 
It will save others time having to look at the JS file and writing their own to use the plugin with Typescript.

All the best,
Jonathan Smart
07976 354770

**Comment by samzilverberg** [comment]
i cloned your branch, made the rename refactor we discussed, merged into master, tagged and released (2.2.0)

thanks for contributing!

**Pull request merged**
