### PR TITLE
Improve error system

### PR DESCRIPTION
**Pull request by damienfa**

### CODE REVIEW

**Comment by samzilverberg** [comment]
looks like a nice small improvement, but the PR is not in mergeable state.
can you merge latest master into your branch before please?

**Comment by damienfa** [comment]
(sorry for the delay) 
I've finally merged my branch. Up to you.

**Comment by samzilverberg** [comment]
omg github is showing me 128 file changes atm and its impossible to compare to master.
I get this problem sometimes and usually repulling/repushing puts github back into sync.
If you can do it it would be great, I can probably get to it this weekend if you dont.

**Comment by damienfa** [comment]
Yes, it's because since 3th May (day of my PR), you have improved the branch, and now, to push my PR I had to pull it all on my branch (which generate 128 files changes...).
I propose something easier :  I close that PR, I close my fork, I clone from the latest version of the code, and I commit/push my change on that new version.

**Pull request closed without merging**
